### ISSUE TITLE
who's the fairest of them all?

### ISSUE THREAD

**Issue by rueberger** [peterpanning/magicmirror#1]

**Comment by rueberger** [comment]
bump

**Comment by peterpanning** [comment]
You are the fairest of them all, 

So says this mirror on the wall

**Comment by nherson** [comment]
Me. It's me.

**Comment by peterpanning** [comment]
<iframe src="//giphy.com/embed/bHd02S4Uqmpji" width="480" height="217" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="http://giphy.com/gifs/ron-weasley-always-bHd02S4Uqmpji">via GIPHY</a></p>

**Comment by peterpanning** [comment]
![](http://giphy.com/gifs/ron-weasley-always-bHd02S4Uqmpji)

**Comment by peterpanning** [comment]
![](http://giphy.com/gifs/bHd02S4Uqmpji/html5)
